"""initial schema

Revision ID: 161c76e2c112
Revises: 
Create Date: 2026-09-02 04:51:04.013579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161c76e2c112'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('RECRUITER', 'INTERVIEWER', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('job_openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ARCHIVED', name='job_status'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_openings_department'), 'job_openings', ['department'], unique=False)
    op.create_index(op.f('ix_job_openings_status'), 'job_openings', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('candidate_email', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('applied_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('current_stage', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', name='application_stage'), nullable=False),
    sa.Column('stage_entered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('previous_stage_before_rejection', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', name='application_stage'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_openings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_candidate_email'), 'applications', ['candidate_email'], unique=False)
    op.create_index(op.f('ix_applications_candidate_name'), 'applications', ['candidate_name'], unique=False)
    op.create_index(op.f('ix_applications_current_stage'), 'applications', ['current_stage'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index('ix_applications_job_stage', 'applications', ['job_id', 'current_stage'], unique=False)
    op.create_index(op.f('ix_applications_source'), 'applications', ['source'], unique=False)
    op.create_index(op.f('ix_applications_stage_entered_at'), 'applications', ['stage_entered_at'], unique=False)
    op.create_index(op.f('ix_applications_updated_at'), 'applications', ['updated_at'], unique=False)
    op.create_table('alert_dismissals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', name='application_stage'), nullable=False),
    sa.Column('stage_entered_at', sa.DateTime(), nullable=False),
    sa.Column('dismissed_by', sa.Integer(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dismissed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'stage', 'stage_entered_at', name='uq_alert_dismissal_episode')
    )
    op.create_index(op.f('ix_alert_dismissals_application_id'), 'alert_dismissals', ['application_id'], unique=False)
    op.create_table('application_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'STAGE_CHANGE', 'REJECTED', 'REINSTATED', 'FEEDBACK', 'INTERVIEW_SCHEDULED', 'INTERVIEWER_ASSIGNED', 'INTERVIEWER_REMOVED', name='history_event_type'), nullable=False),
    sa.Column('from_stage', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', name='application_stage'), nullable=True),
    sa.Column('to_stage', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', name='application_stage'), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_history_application_id'), 'application_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_history_created_at'), 'application_history', ['created_at'], unique=False)
    op.create_table('application_panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'interviewer_id', name='uq_application_interviewer')
    )
    op.create_index(op.f('ix_application_panel_application_id'), 'application_panel', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_panel_interviewer_id'), 'application_panel', ['interviewer_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_application_id'), 'feedback', ['application_id'], unique=False)
    op.create_index(op.f('ix_feedback_interviewer_id'), 'feedback', ['interviewer_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('interview_type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_interviews_date'), 'interviews', ['date'], unique=False)
    op.create_table('interview_interviewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_interviewers_interview_id'), 'interview_interviewers', ['interview_id'], unique=False)
    op.create_index(op.f('ix_interview_interviewers_interviewer_id'), 'interview_interviewers', ['interviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_interviewers_interviewer_id'), table_name='interview_interviewers')
    op.drop_index(op.f('ix_interview_interviewers_interview_id'), table_name='interview_interviewers')
    op.drop_table('interview_interviewers')
    op.drop_index(op.f('ix_interviews_date'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_feedback_interviewer_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_application_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_application_panel_interviewer_id'), table_name='application_panel')
    op.drop_index(op.f('ix_application_panel_application_id'), table_name='application_panel')
    op.drop_table('application_panel')
    op.drop_index(op.f('ix_application_history_created_at'), table_name='application_history')
    op.drop_index(op.f('ix_application_history_application_id'), table_name='application_history')
    op.drop_table('application_history')
    op.drop_index(op.f('ix_alert_dismissals_application_id'), table_name='alert_dismissals')
    op.drop_table('alert_dismissals')
    op.drop_index(op.f('ix_applications_updated_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_stage_entered_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_source'), table_name='applications')
    op.drop_index('ix_applications_job_stage', table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_current_stage'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_name'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_email'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_job_openings_status'), table_name='job_openings')
    op.drop_index(op.f('ix_job_openings_department'), table_name='job_openings')
    op.drop_table('job_openings')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
