"""add index on applied_date

Revision ID: 45b1be0b5b48
Revises: 161c76e2c112
Create Date: 2026-09-02 12:43:11.323834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b1be0b5b48'
down_revision = '161c76e2c112'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_applied_date'), 'applications', ['applied_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_applied_date'), table_name='applications')
    # ### end Alembic commands ###
